README.md
To improve the information available in the README file and to be
compliant with the OS requirements of the organization, add sections to
the README that include some description of the CoC, security and
license associated with the project
=> Add license, code of conduct and security information to the README

src/pytest_memray/plugin.py, tests/test_pytest_pensieve.py
Some pytest functionality relies of the fact that the "longrepr"
attribute is not None for failing tests. According to pytest type
annotations this can be a string explaining why the test failed or some
complicated traceback object. As we cannot easily make a traceback
object, we can simply put a string explaining why the test failed.
=> Ensure the "longrepr" attribute is set on failing tests

.github/workflows/build_dist.yml
Resolves #9.
As I don't have write access on the REPO the GHA is not run here, but you can see it run on my fork here. https://github.com/gaborbernat/pytest-memray/runs/6377932791?check_suite_focus=true:
```
Successfully built pytest-memray-1.0.0.tar.gz and pytest_memray-1.0.0-py3-none-any.whl
```
=> Release wheels besides sdist too

docs/configuration.rst, docs/news/10.feature.rst, src/pytest_memray/plugin.py, src/pytest_memray/utils.py, tests/test_pytest_pensieve.py, tests/unit/test_utils.py
This allows users to run flamegraph (and other) dumps on a test case
run.
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
Resolves #10.
=> Allow to persist binary dumps past test suite run

README.md, docs/configuration.rst, docs/news/28.feature.rst, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
And if set recreate it if already exists. Print the number of dumps
generated in the summary.
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
Resolves #28.
=> Allow specifying the bin path prefix

pyproject.toml
The Python versions badge in the README is missing Python 3.11, and I believe this is what's needed to add it.
None whatsoever 😄
=> Declare Python 3.11 support

pyproject.toml, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
The 'flaky' plugging does some cuestionable activity and forces our
plugin to be called with itself. This causes us to wrap our own test
wrapper and therefore create nested Trackers, which is not allowed.
To fix this, unwrap the test function at the end of the run.
*Issue number of the reported bug or feature request: #<number>*
=> Fix incompatibility with the 'flaky' plugin

pyproject.toml, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
The pytest-xdist plugin spawns worker processes that run the tests while
the main process reports the results. As every process has its own copy
of all the plugins, this means that when the main process reports the
final summary, it doesn't have access to the results stored by every
individual test so the plugin is unable to print the summary.
To make ourselves compatible with pytest-xdist, we make the main process
and the workers use a common path to store the metadata and result files
(this is communicated from the main process to the workers by an
environment variable). Then, at report time, if the main process doesn't
have any result data, it will fetch it from this directory instead.
Closes: #2
=> Make the plugin compatible with pytest-xdist

docs/news/57.feature.rst, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
The fact that the plugin is not registered if `--memray` is not
provided has proven to be a source of confusion and provides a bad
UX.
Closes: #49
=> Ensure tests marked by memray run even if `--memray` is not passed

README.md, docs/news/58.feature.rst, src/pytest_memray/marks.py, src/pytest_memray/plugin.py, src/pytest_memray/utils.py, tests/test_pytest_memray.py
To allow users to get as much information as they need, add two new
options to the command line invocation that allows to:
* Customize how many stacks to show for every allocation.
* Obtain native traces and show the hybrid stack.
*Issue number of the reported bug or feature request: #<number>*
=> Allow to customize the tracebacks one error

docs/news/60.bugfix.rst, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
Pytest shows a warning if we return something from the
pytest_pyfunc_call wrapper as it interprets this as the test returning a
value. We are incorrecly returning the pytest test result from the
wrapper instead of whatever the test returns.
Closes: #60
=> Do not return our result from the pytest_pyfunc_call wrapper

src/pytest_memray/plugin.py, tests/test_pytest_memray.py
This fixes the `OSError` caused by long capture file names in our temporary directory when `--memray-bin-path` is not in use by `pytest-xdist` is.
Relates-to: #68
=> Fix long test names with xdist

docs/configuration.rst
*Issue number of the reported bug or feature request: #64*
Adds documentation for two command line options added in https://github.com/bloomberg/pytest-memray/pull/58.
N/A
=> Document command line options `stacks` and `native`

tests/test_pytest_memray.py
When using `pytest-xdist` there are some extra allocations that the
plugin does that make it quite difficult to test values for the `limit`
decorator that are close to the numeric limit. In particular this is a
sample list of allocations in Python 3.11 when the plugin is active:
```
List of allocations:
- 628.0B allocated here:
channel_data:/lib/python3.11/site-packages/execnet/gateway_base.py:476
- 534.0B allocated here:
_local_receive:/lib/python3.11/site-packages/execnet/gateway_base.py:856
- 772.0B allocated here:
handle_command:/lib/python3.11/site-packages/xdist/remote.py:128
- 1.0KiB allocated here:
valloc:/lib/python3.11/site-packages/memray/_test.py:44
- 862.0B allocated here:
_thread_receiver:/lib/python3.11/site-packages/execnet/gateway_base.py:969
```
The only one the test …
=> Relax the sizes in the 'test_limit_memory_marker_with_pytest_xdist' test

README.md, docs/configuration.rst, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
=> Support passing --trace-python-allocators to memray

Makefile, pyproject.toml, tox.ini
Ruff is more complete and performant
*Issue number of the reported bug or feature request: #<number>*
=> Use ruff instead of flake8 + isort

README.md
Fix the bulleted lists in README.md
=> [Docs] Fix the bulleted lists in README.md

src/pytest_memray/plugin.py, src/pytest_memray/utils.py, tests/test_pytest_memray.py
In the docs we say that a value of 0 will show all entries but
currently the plugin crashes because it interprets the value of 0 as a
string and is not properly propagated to show all entries.
*Issue number of the reported bug or feature request: #46
=> Fix --most-allocations with the value of 0

.github/workflows/build.yml, .github/workflows/build_dist.yml, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
These no longer trigger a warning with the current versions of mypy,
pytest, and pluggy. It looks as though these calls have been typed since
pluggy 1.2.0, which was released 3 months ago.
We didn't notice this because our lint checks weren't scheduled to run on a schedule. This PR fixes that as well.
=> Drop `# type: ignore` comments for `@hookimpl`

README.md, docs/configuration.rst, docs/news/91.feature.rst, src/pytest_memray/marks.py, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
As requested from some users, add a new --fail-on-increase option that
makes the test run fail if the memory usage increases from previous runs
in tests marked with "limit_memory".
*Issue number of the reported bug or feature request: #7 
closes: #7
=> Add a new --fail-on-increase option

docs/news/107.feature.rst, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
This reduces the amount of temporary disk space needed while running tests.
=> Use aggregated capture files

.github/workflows/build.yml, tests/test_pytest_memray.py, tox.ini
Fix a few different issues that I noticed while working on #103:
1. The `PYTEST_ADDOPTS` environment variable wasn't being passed through to pytest by tox, apparently due to our config file not using a wildcard where we meant to.
2. Tox wasn't exercising Python 3.11 or 3.12 by default (even though our CI exercised them)
3. One of our tests would fail if run in isolation due to libpthread "leaking" memory by saving a thread and its stack for later reuse.
=> Improve tests

docs/news/113.bugfix.rst, src/pytest_memray/plugin.py, tests/test_utils.py
When all allocations are the same size, we were falling back to the size of the smallest allocation as our step for generating histogram buckets. When the smallest allocation was zero bytes, that would lead to a division by zero and an exception.
Fix this by falling back to 1 instead of the size of the smallest allocation. This will never lead to a zero division error, and still puts every element in the same bucket because they're all equal (otherwise we wouldn't have needed the fallback).
Closes #93
=> Ensure our histogram uses a non-zero step

pyproject.toml, src/pytest_memray/plugin.py, tests/test_pytest_memray.py
`anyio` allows running `async def` test functions, but the wrapper installed by Memray to add tracking around the test function breaks `anyio`'s detection.
Work around this by using an `async def` wrapper when the function being wrapped is a coroutine function.
Closes #119
=> Cooperate with anyio

docs/configuration.rst
Single backticks are used for cross references in reStructuredText. Double backticks are used for code formatting.
=> docs: Fix markup in configuration.rst
